name: "Pnpm Install"
description: "Try to install pnpm and duck out"
inputs:
  recursiveInstall: # id of input
    description: "Recursively install NPM packages"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Cache pnpm modules
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**pnpm-lock.yaml') }}

    - uses: pnpm/action-setup@v2.0.1
      if: steps.cache.outputs.cache-hit != 'true'
      with:
        version: 6.25.1
        run_install: ${{inputs.recursiveInstall}}
